FROM golang:1.23
WORKDIR /usr/src/app
COPY ./app/api/go/go.mod ./app/api/go/go.sum ./
RUN go mod download && go mod verify
#cache install
RUN go build -v std 
COPY ./app/api/go .
RUN go build -v -o /usr/local/bin/ ./...