version: "3.3"
services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    shm_size: 8g
    container_name: postgres_gethold
    networks:
      - net
    volumes:
      - ./volumes/.postgres:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - PGPASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_RO_PASSWORD=${DB_RO_PASSWORD}
      - DB_RO_USER=${DB_RO_USER}

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; server'
    container_name: org
    volumes:
      - ./.env:/org/.env
      - ./frontend/:/www/
    networks:
      - net
    ports:
      - 8080:8080
    depends_on:
      - db

networks:
    net:
        driver: bridge
