// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEvent = "Event"

// Event mapped from table <Event>
type Event struct {
	ID        int32     `gorm:"column:id;not null" json:"id"`
	Name      string    `gorm:"column:name" json:"name"`
	Begindate time.Time `gorm:"column:begindate" json:"begindate"`
	Enddate   time.Time `gorm:"column:enddate" json:"enddate"`
	Details   string    `gorm:"column:details" json:"details"`
	Architect int32     `gorm:"column:architect;not null" json:"architect"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
