// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEventmanager = "eventmanager"

// Eventmanager mapped from table <eventmanager>
type Eventmanager struct {
	ID        int32 `gorm:"column:id" json:"id"`
	Managerid int32 `gorm:"column:managerid" json:"managerid"`
	Eventid   int32 `gorm:"column:eventid" json:"eventid"`
}

// TableName Eventmanager's table name
func (*Eventmanager) TableName() string {
	return TableNameEventmanager
}
