// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameManager = "manager"

// Manager mapped from table <manager>
type Manager struct {
	ID             int32     `gorm:"column:id" json:"id"`
	Name           string    `gorm:"column:name" json:"name"`
	Birthday       time.Time `gorm:"column:birthday" json:"birthday"`
	Qualifications string    `gorm:"column:qualifications" json:"qualifications"`
	Photo          string    `gorm:"column:photo" json:"photo"`
	Bio            string    `gorm:"column:bio" json:"bio"`
}

// TableName Manager's table name
func (*Manager) TableName() string {
	return TableNameManager
}
