// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSchedule = "schedule"

// Schedule mapped from table <schedule>
type Schedule struct {
	ID          int32     `gorm:"column:id" json:"id"`
	Eventid     int32     `gorm:"column:eventid" json:"eventid"`
	Managerid   int32     `gorm:"column:managerid" json:"managerid"`
	Volunteerid int32     `gorm:"column:volunteerid" json:"volunteerid"`
	Startdate   time.Time `gorm:"column:startdate" json:"startdate"`
	Enddate     time.Time `gorm:"column:enddate" json:"enddate"`
	Weakly      bool      `gorm:"column:weakly" json:"weakly"`
}

// TableName Schedule's table name
func (*Schedule) TableName() string {
	return TableNameSchedule
}
