// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int32  `gorm:"column:id" json:"id"`
	Password  string `gorm:"column:password" json:"password"`
	User      string `gorm:"column:user" json:"user"`
	Role      int32  `gorm:"column:role" json:"role"`
	Profileid int32  `gorm:"column:profileid" json:"profileid"`
	Token     string `gorm:"column:token" json:"token"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
