// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVolunteer = "volunteer"

// Volunteer mapped from table <volunteer>
type Volunteer struct {
	ID       int32     `gorm:"column:id" json:"id"`
	Name     string    `gorm:"column:name" json:"name"`
	Birthday time.Time `gorm:"column:birthday" json:"birthday"`
	Photo    string    `gorm:"column:photo" json:"photo"`
	Bio      string    `gorm:"column:bio" json:"bio"`
}

// TableName Volunteer's table name
func (*Volunteer) TableName() string {
	return TableNameVolunteer
}
